export const dummyData = [
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "The body of the Egyptian Sphinx was based on which animal?",
    correct_answer: "Lion",
    incorrect_answers: ["Bull", "Horse", "Dog"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "What is the capital of Denmark?",
    correct_answer: "Copenhagen",
    incorrect_answers: ["Aarhus", "Odense", "Aalborg"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "What country is the second largest in the world by area?",
    correct_answer: "Canada",
    incorrect_answers: ["Russia", "China", "United States of America"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "What is the largest country in the world ?",
    correct_answer: "Russian Federation",
    incorrect_answers: ["China", "Canada", "Brazil"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "Which of the following Japanese islands is the biggest?",
    correct_answer: "Honshu",
    incorrect_answers: ["Hokkaido", "Shikoku", "Kyushu"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "What is the capital of Jamaica?",
    correct_answer: "Kingston",
    incorrect_answers: ["San Juan", "Port-au-Prince", "Bridgetown"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "What is the capital of India?",
    correct_answer: "New Delhi",
    incorrect_answers: ["Bejing", "Montreal", "Tithi"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "Which of the following former Yugoslavian states is landlocked?",
    correct_answer: "Serbia",
    incorrect_answers: ["Bosnia and Herzegovina", "Montenegro", "Croatia"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "What is the Polish city known to Germans as Danzig?",
    correct_answer: "Gdańsk",
    incorrect_answers: ["Warsaw", "Zakopane", "Poznań"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "The Space Needle is located in which city?",
    correct_answer: "Seattle",
    incorrect_answers: ["Los Angles", "Toronto", "Vancouver"],
  },
];
